services:
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./src:/var/www/html
    depends_on:
      - php-fpm
  php-fpm:
    build: ./build/php/
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./config/php/zz-php-fpm.ini:/usr/local/etc/php-fpm.d/zz-php-fpm.ini:ro
      - ./config/php/zz-php.ini:/usr/local/etc/php/conf.d/zz-php.ini:ro
    depends_on:
      - db
    environment:
      DB_HOST: "db" # The db service
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  caddy_data:
  caddy_config:
